### ISSUE TITLE
Models for testing

### ISSUE THREAD

**Issue by nikky4D** [anuragranj/humanflow#1]
Hi,

Though you don't have the full code, Would you have the models available for testing?

**Comment by anuragranj** [comment]
We will start releasing code, models and data starting this week.

**Comment by billamiable** [comment]
Looking forward to see the trained model :)

**Comment by anuragranj** [comment]
Models and data are up.

**Comment by billamiable** [comment]
Hi,
I'm new to torch. I wonder if i want to generate optical flow. DO I need to place the following code in a lua file and run `th xx.lua`?
```
stn = require 'stn'
bodynet = require 'bodynet'
easyComputeFlow = bodynet.easy_setup('pretrained/human_flow_model_[noise_adaptive].t7'):cuda()
im1 = image.load(<IMAGE_PATH_1>, 3, 'float')
im2 = image.load(<IMAGE_PATH_2>, 3, 'float')
flow = easyComputeFlow(im1, im2)
```

Thanks!

**Comment by anuragranj** [comment]
Yes. That should work. You would also need `require 'image' ` for using the `image` library.

**Comment by billamiable** [comment]
Hi @anuragranj , when I try the previous method, i got the following error in the line "`easyComputeFlow = bodynet.easy_setup('pretrained/human_flow_model_noise_adaptive.t7'):cuda()`":
```
Loaded modelpretrained/human_flow_model_noise_adaptive.t7	
/home/xxx/torch/install/bin/luajit: output.lua:6: attempt to index a function value
stack traceback:
	output.lua:6: in main chunk
	[C]: in function 'dofile'
	...xx/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50

```

do you know how to deal with it? Thanks in advance!

**Comment by anuragranj** [comment]
Thanks for pointing out. It was a bug, and its fixed in recent [commit](https://github.com/anuragranj/humanflow/commit/9abcfef53e06b2a1e9532800bfead93984cb0a59)  

Also, `:cuda()` should not be there as updated in README.md.

**Comment by billamiable** [comment]
Cool, Thanks for the quick reply, meanwhile i found the result is as expected if i use t+1 input as img1, t input as img2. DO you see similar problem? @anuragranj 
(I use `flowExtensions.writeFLO('xx.flo',flow)` to write into flo file and visualize in Matlab)

**Comment by anuragranj** [comment]
you can also use `flowExtensions.xy2rgb(flow[1], flow[2])` to visualize.

Also you are somewhat right. Our spatial coordinates for flow representation are inverted. So, the correct flow would be -flow(im1, im2), meaning you would need to invert the directions. This is consistent with dataset and predictions from the model.

So, you would want to use `flowExtensions.writeFLO('xx.flo',-flow)`, given that you use t as img1 and t+1 as img2.

I will write a note in the README.md addressing this.

**Comment by billamiable** [comment]
Ok, thanks

bty, if only add `flowExtensions.xy2rgb(flow[1], flow[2])`, there will be an another error:
`torch.DoubleTensor expected, got torch.FloatTensor`. Maybe you can add one th file along with the released code, therefore it will be more convenient for those who are not familiar with torch to test.

**Comment by anuragranj** [comment]
Oh, in that case, you should just set torch default tensor to float using this line in your code.
`torch.setdefaulttensortype('torch.FloatTensor')`
I will make a demo file.

**Comment by anuragranj** [comment]
I have added `demo.lua` and added a note on flow coordinate representation used in the representation in `README.md` . Please let me know if something is not clear. 
Thanks.
