### ISSUE TITLE
Download dataset: Permission Denied

### ISSUE THREAD

**Issue by lucasgamez** [anuragranj/humanflow#3]
Hello,

I wanted to use your dataset in order to train some model that compute optical flow, but I am not able to download it from your website. I am getting a permission denied error.
Do you have an idea why this happening? Did your sharing policy change or something?

**Comment by anuragranj** [comment]
Hi @lucasgamez 
At the moment, wget doesn't work. Can you try downloading directly from the webpage http://humanflow.is.tue.mpg.de/ by clicking on the individual links? This works for me.

**Comment by lucasgamez** [comment]
I opened this issue because the link on the webpage also gave me the permission denied the last time I tried (~16 hours ago). But now it seems to work, I don't really know why.

Anyway, thank you for your help and your quick answer.

**Comment by anuragranj** [comment]
Well sometimes, it blocks an ip if there are too many requests from it in a short time.

**Comment by lucasgamez** [comment]
I run several times the wget command to find out why it wasn't working. I wanted to escape from clicking on every links (well, I can't).
Problem solved, I close the issue.
Thank you.

**Comment by lucasgamez** [comment]
Hello,
I reopen the issue because I havn't finish the download of the dataset and it's been several days that I am getting the permission denied error whatever the connection used. 
I don't think it is because I spammed the links anymore. Do you have any idea ?

**Comment by anuragranj** [comment]
I still see that I can download the links from the page. And this works on different machines. Can you try downloading from a different computer and see if it works.

**Comment by lucasgamez** [comment]
I tried with different computer and different connection, it still giving me the same error.
Every links redirect me on http://psfiles.is.tuebingen.mpg.de:3000/static_pages/no_permission .

**Comment by anuragranj** [comment]
That's strange. Okay, so I am using chrome browser. Can you email me your IP address, and I can get it checked?

**Comment by anuragranj** [comment]
Resolved.

**Comment by lhoangan** [comment]
Hi,

It's the same case for me. I couldn't download by clicking on the links because of permission denied `http://psfiles.is.tuebingen.mpg.de:3000/static_pages/no_permission`
I've tried different machine and web browser (chrome, firefox) as well.

@lucasgamez did you manage to auto-download them or you had to go through and click on every single one of them?

**Comment by anuragranj** [comment]
Hi @lhoangan 
You would need to download them manually using a browser. The auto-download is disabled.

**Comment by lhoangan** [comment]
Hi @anuragranj yes I was trying to download them manually, but clicking does not work as well. I kept receiving permission denied error.

**Comment by anuragranj** [comment]
Which file in particular gives you an error?

**Comment by lhoangan** [comment]
I didn't try all of them, but the first and any random pick does bounce back an error. So I would say that could be all.

**Comment by anuragranj** [comment]
Can you try again? I can download them without any problem. Even on my phone.

**Comment by lhoangan** [comment]
It's still the same error.

**Comment by anuragranj** [comment]
This doesn't make sense. @lucasgamez had no problems downloading by manually clicking the link on the website. I want to clarify if you are using the link on the page here. http://humanflow.is.tue.mpg.de
The static links such as these WILL NOT work: 
http://psfiles.is.tuebingen.mpg.de:3000/downloads/humanflow/HumanFlowDataset_7z_042

**Comment by lhoangan** [comment]
May I ask which system are you using? I'm using Firefox and Chrome on Linux Mint and my colleague as well, and we got the same error. Yes, I assure we did click on the links.

**Comment by anuragranj** [comment]
I verified it on the following systems:
- Ubuntu with Firefox
- Ubuntu with Chrome
- Windows with Chrome
- Windows with Edge
- Mac with Safari
- Mac with Chrome
- Android with Chrome

**Comment by lhoangan** [comment]
I'll try to find a machine with these setting, though I'm not sure if it would solve. Do you have any idea of what might cause the problem? I didn't even try to wget, so why our machines are blocked?

**Comment by anuragranj** [comment]
This is very strange. I would expect it to depend only on browser, and not on OS. I will try to test it on Mint soon.

**Comment by lhoangan** [comment]
As I can see from previous conversion in this thread, you mentioned that an IP might get blocked if there are many requests in a short time. Is there any chance that it could be my case, though I'm not sure why since it's my first time to try to download them and I got the error the first time clicking on the link. And given that there're dozens of them, can you recommend how many parallel download should I run so that I won't be blocked?

**Comment by anuragranj** [comment]
I could launch all the download links in parallel without any error. The denial comes only if several wget requests are made to the server for automatic downloads which doesn't work anyway. I can get your IP checked if you send it over email.

**Comment by lhoangan** [comment]
Seems like I can now download some of them now. Did you unlock my IP? Could it be  someone from the same institute tried wget and got the whole institute blocked? Maybe putting a warning before the downloading list could help others who come in later. Thank you for your support.

**Comment by anuragranj** [comment]
Okay. Did you manage to download everything? Can you tell me if there is anything that fails now?

**Comment by lhoangan** [comment]
Everything is good for me. I got all the files already.

**Comment by anuragranj** [comment]
Perfect.
